trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
  - job: UnitTest
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.37.0-x86_64-pc-windows-msvc'
      - script: make test
        displayName: Run unit tests

  - job: UnitTestAllFeatures
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.37.0-x86_64-pc-windows-msvc'
      - script: make test-all-features
        displayName: Run unit tests with all features
