[package]
name = "ckb-vm"
version = "0.1.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
byteorder = "1"
goblin = "0.0.20"
memmap = "0.7.0"
libc = "0.2.47"
fnv = "1.0.6"

[build-dependencies]
cc = "1.0"
