[package]
name = "ckb-vm"
version = "0.1.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"

[features]
default = []

jit = ["memmap", "libc"]

[dependencies]
byteorder = "1"
goblin = "0.0.21"
memmap = { version = "0.7.0", optional = true }
libc = { version = "0.2.47", optional = true }
fnv = "1.0.6"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
criterion = "0.2.10"
proptest = "0.9.1"

[[bench]]
name = "bits_benchmark"
harness = false
